/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedVesselScreeningRouteImport } from './routes/_authed/vessel-screening'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedPortIntelligenceRouteImport } from './routes/_authed/port-intelligence'
import { Route as AuthedGlossaryRouteImport } from './routes/_authed/glossary'
import { Route as AuthedFixtureMarketRouteImport } from './routes/_authed/fixture-market'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedCounterpartyDdRouteImport } from './routes/_authed/counterparty-dd'
import { Route as AuthedChatsRouteImport } from './routes/_authed/chats'
import { Route as AuthedVesselScreeningIndexRouteImport } from './routes/_authed/vessel-screening/index'
import { Route as AuthedCounterpartyDdIndexRouteImport } from './routes/_authed/counterparty-dd/index'
import { Route as AuthedVesselScreeningNewRouteImport } from './routes/_authed/vessel-screening/new'
import { Route as AuthedVesselScreeningScreeningIdRouteImport } from './routes/_authed/vessel-screening/$screeningId'
import { Route as AuthedCounterpartyDdNewRouteImport } from './routes/_authed/counterparty-dd/new'
import { Route as AuthedCounterpartyDdProjectIdRouteImport } from './routes/_authed/counterparty-dd/$projectId'
import { Route as AuthedVesselScreeningMonitoringIndexRouteImport } from './routes/_authed/vessel-screening/monitoring/index'
import { Route as AuthedVesselScreeningBatchIndexRouteImport } from './routes/_authed/vessel-screening/batch/index'
import { Route as AuthedVesselScreeningMonitoringMonitorIdRouteImport } from './routes/_authed/vessel-screening/monitoring/$monitorId'
import { Route as AuthedVesselScreeningBatchBatchIdRouteImport } from './routes/_authed/vessel-screening/batch/$batchId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedVesselScreeningRoute = AuthedVesselScreeningRouteImport.update({
  id: '/vessel-screening',
  path: '/vessel-screening',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPortIntelligenceRoute = AuthedPortIntelligenceRouteImport.update({
  id: '/port-intelligence',
  path: '/port-intelligence',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGlossaryRoute = AuthedGlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFixtureMarketRoute = AuthedFixtureMarketRouteImport.update({
  id: '/fixture-market',
  path: '/fixture-market',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCounterpartyDdRoute = AuthedCounterpartyDdRouteImport.update({
  id: '/counterparty-dd',
  path: '/counterparty-dd',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedChatsRoute = AuthedChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedVesselScreeningIndexRoute =
  AuthedVesselScreeningIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedVesselScreeningRoute,
  } as any)
const AuthedCounterpartyDdIndexRoute =
  AuthedCounterpartyDdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedCounterpartyDdRoute,
  } as any)
const AuthedVesselScreeningNewRoute =
  AuthedVesselScreeningNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthedVesselScreeningRoute,
  } as any)
const AuthedVesselScreeningScreeningIdRoute =
  AuthedVesselScreeningScreeningIdRouteImport.update({
    id: '/$screeningId',
    path: '/$screeningId',
    getParentRoute: () => AuthedVesselScreeningRoute,
  } as any)
const AuthedCounterpartyDdNewRoute = AuthedCounterpartyDdNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedCounterpartyDdRoute,
} as any)
const AuthedCounterpartyDdProjectIdRoute =
  AuthedCounterpartyDdProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthedCounterpartyDdRoute,
  } as any)
const AuthedVesselScreeningMonitoringIndexRoute =
  AuthedVesselScreeningMonitoringIndexRouteImport.update({
    id: '/monitoring/',
    path: '/monitoring/',
    getParentRoute: () => AuthedVesselScreeningRoute,
  } as any)
const AuthedVesselScreeningBatchIndexRoute =
  AuthedVesselScreeningBatchIndexRouteImport.update({
    id: '/batch/',
    path: '/batch/',
    getParentRoute: () => AuthedVesselScreeningRoute,
  } as any)
const AuthedVesselScreeningMonitoringMonitorIdRoute =
  AuthedVesselScreeningMonitoringMonitorIdRouteImport.update({
    id: '/monitoring/$monitorId',
    path: '/monitoring/$monitorId',
    getParentRoute: () => AuthedVesselScreeningRoute,
  } as any)
const AuthedVesselScreeningBatchBatchIdRoute =
  AuthedVesselScreeningBatchBatchIdRouteImport.update({
    id: '/batch/$batchId',
    path: '/batch/$batchId',
    getParentRoute: () => AuthedVesselScreeningRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/chats': typeof AuthedChatsRoute
  '/counterparty-dd': typeof AuthedCounterpartyDdRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/fixture-market': typeof AuthedFixtureMarketRoute
  '/glossary': typeof AuthedGlossaryRoute
  '/port-intelligence': typeof AuthedPortIntelligenceRoute
  '/settings': typeof AuthedSettingsRoute
  '/vessel-screening': typeof AuthedVesselScreeningRouteWithChildren
  '/counterparty-dd/$projectId': typeof AuthedCounterpartyDdProjectIdRoute
  '/counterparty-dd/new': typeof AuthedCounterpartyDdNewRoute
  '/vessel-screening/$screeningId': typeof AuthedVesselScreeningScreeningIdRoute
  '/vessel-screening/new': typeof AuthedVesselScreeningNewRoute
  '/counterparty-dd/': typeof AuthedCounterpartyDdIndexRoute
  '/vessel-screening/': typeof AuthedVesselScreeningIndexRoute
  '/vessel-screening/batch/$batchId': typeof AuthedVesselScreeningBatchBatchIdRoute
  '/vessel-screening/monitoring/$monitorId': typeof AuthedVesselScreeningMonitoringMonitorIdRoute
  '/vessel-screening/batch/': typeof AuthedVesselScreeningBatchIndexRoute
  '/vessel-screening/monitoring/': typeof AuthedVesselScreeningMonitoringIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/chats': typeof AuthedChatsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/fixture-market': typeof AuthedFixtureMarketRoute
  '/glossary': typeof AuthedGlossaryRoute
  '/port-intelligence': typeof AuthedPortIntelligenceRoute
  '/settings': typeof AuthedSettingsRoute
  '/counterparty-dd/$projectId': typeof AuthedCounterpartyDdProjectIdRoute
  '/counterparty-dd/new': typeof AuthedCounterpartyDdNewRoute
  '/vessel-screening/$screeningId': typeof AuthedVesselScreeningScreeningIdRoute
  '/vessel-screening/new': typeof AuthedVesselScreeningNewRoute
  '/counterparty-dd': typeof AuthedCounterpartyDdIndexRoute
  '/vessel-screening': typeof AuthedVesselScreeningIndexRoute
  '/vessel-screening/batch/$batchId': typeof AuthedVesselScreeningBatchBatchIdRoute
  '/vessel-screening/monitoring/$monitorId': typeof AuthedVesselScreeningMonitoringMonitorIdRoute
  '/vessel-screening/batch': typeof AuthedVesselScreeningBatchIndexRoute
  '/vessel-screening/monitoring': typeof AuthedVesselScreeningMonitoringIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/chats': typeof AuthedChatsRoute
  '/_authed/counterparty-dd': typeof AuthedCounterpartyDdRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/fixture-market': typeof AuthedFixtureMarketRoute
  '/_authed/glossary': typeof AuthedGlossaryRoute
  '/_authed/port-intelligence': typeof AuthedPortIntelligenceRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/vessel-screening': typeof AuthedVesselScreeningRouteWithChildren
  '/_authed/counterparty-dd/$projectId': typeof AuthedCounterpartyDdProjectIdRoute
  '/_authed/counterparty-dd/new': typeof AuthedCounterpartyDdNewRoute
  '/_authed/vessel-screening/$screeningId': typeof AuthedVesselScreeningScreeningIdRoute
  '/_authed/vessel-screening/new': typeof AuthedVesselScreeningNewRoute
  '/_authed/counterparty-dd/': typeof AuthedCounterpartyDdIndexRoute
  '/_authed/vessel-screening/': typeof AuthedVesselScreeningIndexRoute
  '/_authed/vessel-screening/batch/$batchId': typeof AuthedVesselScreeningBatchBatchIdRoute
  '/_authed/vessel-screening/monitoring/$monitorId': typeof AuthedVesselScreeningMonitoringMonitorIdRoute
  '/_authed/vessel-screening/batch/': typeof AuthedVesselScreeningBatchIndexRoute
  '/_authed/vessel-screening/monitoring/': typeof AuthedVesselScreeningMonitoringIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/chats'
    | '/counterparty-dd'
    | '/dashboard'
    | '/fixture-market'
    | '/glossary'
    | '/port-intelligence'
    | '/settings'
    | '/vessel-screening'
    | '/counterparty-dd/$projectId'
    | '/counterparty-dd/new'
    | '/vessel-screening/$screeningId'
    | '/vessel-screening/new'
    | '/counterparty-dd/'
    | '/vessel-screening/'
    | '/vessel-screening/batch/$batchId'
    | '/vessel-screening/monitoring/$monitorId'
    | '/vessel-screening/batch/'
    | '/vessel-screening/monitoring/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/chats'
    | '/dashboard'
    | '/fixture-market'
    | '/glossary'
    | '/port-intelligence'
    | '/settings'
    | '/counterparty-dd/$projectId'
    | '/counterparty-dd/new'
    | '/vessel-screening/$screeningId'
    | '/vessel-screening/new'
    | '/counterparty-dd'
    | '/vessel-screening'
    | '/vessel-screening/batch/$batchId'
    | '/vessel-screening/monitoring/$monitorId'
    | '/vessel-screening/batch'
    | '/vessel-screening/monitoring'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/register'
    | '/_authed/chats'
    | '/_authed/counterparty-dd'
    | '/_authed/dashboard'
    | '/_authed/fixture-market'
    | '/_authed/glossary'
    | '/_authed/port-intelligence'
    | '/_authed/settings'
    | '/_authed/vessel-screening'
    | '/_authed/counterparty-dd/$projectId'
    | '/_authed/counterparty-dd/new'
    | '/_authed/vessel-screening/$screeningId'
    | '/_authed/vessel-screening/new'
    | '/_authed/counterparty-dd/'
    | '/_authed/vessel-screening/'
    | '/_authed/vessel-screening/batch/$batchId'
    | '/_authed/vessel-screening/monitoring/$monitorId'
    | '/_authed/vessel-screening/batch/'
    | '/_authed/vessel-screening/monitoring/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/vessel-screening': {
      id: '/_authed/vessel-screening'
      path: '/vessel-screening'
      fullPath: '/vessel-screening'
      preLoaderRoute: typeof AuthedVesselScreeningRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/port-intelligence': {
      id: '/_authed/port-intelligence'
      path: '/port-intelligence'
      fullPath: '/port-intelligence'
      preLoaderRoute: typeof AuthedPortIntelligenceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/glossary': {
      id: '/_authed/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof AuthedGlossaryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/fixture-market': {
      id: '/_authed/fixture-market'
      path: '/fixture-market'
      fullPath: '/fixture-market'
      preLoaderRoute: typeof AuthedFixtureMarketRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/counterparty-dd': {
      id: '/_authed/counterparty-dd'
      path: '/counterparty-dd'
      fullPath: '/counterparty-dd'
      preLoaderRoute: typeof AuthedCounterpartyDdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/chats': {
      id: '/_authed/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthedChatsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/vessel-screening/': {
      id: '/_authed/vessel-screening/'
      path: '/'
      fullPath: '/vessel-screening/'
      preLoaderRoute: typeof AuthedVesselScreeningIndexRouteImport
      parentRoute: typeof AuthedVesselScreeningRoute
    }
    '/_authed/counterparty-dd/': {
      id: '/_authed/counterparty-dd/'
      path: '/'
      fullPath: '/counterparty-dd/'
      preLoaderRoute: typeof AuthedCounterpartyDdIndexRouteImport
      parentRoute: typeof AuthedCounterpartyDdRoute
    }
    '/_authed/vessel-screening/new': {
      id: '/_authed/vessel-screening/new'
      path: '/new'
      fullPath: '/vessel-screening/new'
      preLoaderRoute: typeof AuthedVesselScreeningNewRouteImport
      parentRoute: typeof AuthedVesselScreeningRoute
    }
    '/_authed/vessel-screening/$screeningId': {
      id: '/_authed/vessel-screening/$screeningId'
      path: '/$screeningId'
      fullPath: '/vessel-screening/$screeningId'
      preLoaderRoute: typeof AuthedVesselScreeningScreeningIdRouteImport
      parentRoute: typeof AuthedVesselScreeningRoute
    }
    '/_authed/counterparty-dd/new': {
      id: '/_authed/counterparty-dd/new'
      path: '/new'
      fullPath: '/counterparty-dd/new'
      preLoaderRoute: typeof AuthedCounterpartyDdNewRouteImport
      parentRoute: typeof AuthedCounterpartyDdRoute
    }
    '/_authed/counterparty-dd/$projectId': {
      id: '/_authed/counterparty-dd/$projectId'
      path: '/$projectId'
      fullPath: '/counterparty-dd/$projectId'
      preLoaderRoute: typeof AuthedCounterpartyDdProjectIdRouteImport
      parentRoute: typeof AuthedCounterpartyDdRoute
    }
    '/_authed/vessel-screening/monitoring/': {
      id: '/_authed/vessel-screening/monitoring/'
      path: '/monitoring'
      fullPath: '/vessel-screening/monitoring/'
      preLoaderRoute: typeof AuthedVesselScreeningMonitoringIndexRouteImport
      parentRoute: typeof AuthedVesselScreeningRoute
    }
    '/_authed/vessel-screening/batch/': {
      id: '/_authed/vessel-screening/batch/'
      path: '/batch'
      fullPath: '/vessel-screening/batch/'
      preLoaderRoute: typeof AuthedVesselScreeningBatchIndexRouteImport
      parentRoute: typeof AuthedVesselScreeningRoute
    }
    '/_authed/vessel-screening/monitoring/$monitorId': {
      id: '/_authed/vessel-screening/monitoring/$monitorId'
      path: '/monitoring/$monitorId'
      fullPath: '/vessel-screening/monitoring/$monitorId'
      preLoaderRoute: typeof AuthedVesselScreeningMonitoringMonitorIdRouteImport
      parentRoute: typeof AuthedVesselScreeningRoute
    }
    '/_authed/vessel-screening/batch/$batchId': {
      id: '/_authed/vessel-screening/batch/$batchId'
      path: '/batch/$batchId'
      fullPath: '/vessel-screening/batch/$batchId'
      preLoaderRoute: typeof AuthedVesselScreeningBatchBatchIdRouteImport
      parentRoute: typeof AuthedVesselScreeningRoute
    }
  }
}

interface AuthedCounterpartyDdRouteChildren {
  AuthedCounterpartyDdProjectIdRoute: typeof AuthedCounterpartyDdProjectIdRoute
  AuthedCounterpartyDdNewRoute: typeof AuthedCounterpartyDdNewRoute
  AuthedCounterpartyDdIndexRoute: typeof AuthedCounterpartyDdIndexRoute
}

const AuthedCounterpartyDdRouteChildren: AuthedCounterpartyDdRouteChildren = {
  AuthedCounterpartyDdProjectIdRoute: AuthedCounterpartyDdProjectIdRoute,
  AuthedCounterpartyDdNewRoute: AuthedCounterpartyDdNewRoute,
  AuthedCounterpartyDdIndexRoute: AuthedCounterpartyDdIndexRoute,
}

const AuthedCounterpartyDdRouteWithChildren =
  AuthedCounterpartyDdRoute._addFileChildren(AuthedCounterpartyDdRouteChildren)

interface AuthedVesselScreeningRouteChildren {
  AuthedVesselScreeningScreeningIdRoute: typeof AuthedVesselScreeningScreeningIdRoute
  AuthedVesselScreeningNewRoute: typeof AuthedVesselScreeningNewRoute
  AuthedVesselScreeningIndexRoute: typeof AuthedVesselScreeningIndexRoute
  AuthedVesselScreeningBatchBatchIdRoute: typeof AuthedVesselScreeningBatchBatchIdRoute
  AuthedVesselScreeningMonitoringMonitorIdRoute: typeof AuthedVesselScreeningMonitoringMonitorIdRoute
  AuthedVesselScreeningBatchIndexRoute: typeof AuthedVesselScreeningBatchIndexRoute
  AuthedVesselScreeningMonitoringIndexRoute: typeof AuthedVesselScreeningMonitoringIndexRoute
}

const AuthedVesselScreeningRouteChildren: AuthedVesselScreeningRouteChildren = {
  AuthedVesselScreeningScreeningIdRoute: AuthedVesselScreeningScreeningIdRoute,
  AuthedVesselScreeningNewRoute: AuthedVesselScreeningNewRoute,
  AuthedVesselScreeningIndexRoute: AuthedVesselScreeningIndexRoute,
  AuthedVesselScreeningBatchBatchIdRoute:
    AuthedVesselScreeningBatchBatchIdRoute,
  AuthedVesselScreeningMonitoringMonitorIdRoute:
    AuthedVesselScreeningMonitoringMonitorIdRoute,
  AuthedVesselScreeningBatchIndexRoute: AuthedVesselScreeningBatchIndexRoute,
  AuthedVesselScreeningMonitoringIndexRoute:
    AuthedVesselScreeningMonitoringIndexRoute,
}

const AuthedVesselScreeningRouteWithChildren =
  AuthedVesselScreeningRoute._addFileChildren(
    AuthedVesselScreeningRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedChatsRoute: typeof AuthedChatsRoute
  AuthedCounterpartyDdRoute: typeof AuthedCounterpartyDdRouteWithChildren
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedFixtureMarketRoute: typeof AuthedFixtureMarketRoute
  AuthedGlossaryRoute: typeof AuthedGlossaryRoute
  AuthedPortIntelligenceRoute: typeof AuthedPortIntelligenceRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedVesselScreeningRoute: typeof AuthedVesselScreeningRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedChatsRoute: AuthedChatsRoute,
  AuthedCounterpartyDdRoute: AuthedCounterpartyDdRouteWithChildren,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedFixtureMarketRoute: AuthedFixtureMarketRoute,
  AuthedGlossaryRoute: AuthedGlossaryRoute,
  AuthedPortIntelligenceRoute: AuthedPortIntelligenceRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedVesselScreeningRoute: AuthedVesselScreeningRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
