/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RRouteImport } from './routes/r'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AiGuideRouteImport } from './routes/ai-guide'
import { Route as IndexRouteImport } from './routes/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RRoute = RRouteImport.update({
  id: '/r',
  path: '/r',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AiGuideRoute = AiGuideRouteImport.update({
  id: '/ai-guide',
  path: '/ai-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-guide': typeof AiGuideRoute
  '/privacy': typeof PrivacyRoute
  '/r': typeof RRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-guide': typeof AiGuideRoute
  '/privacy': typeof PrivacyRoute
  '/r': typeof RRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-guide': typeof AiGuideRoute
  '/privacy': typeof PrivacyRoute
  '/r': typeof RRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-guide' | '/privacy' | '/r' | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-guide' | '/privacy' | '/r' | '/terms'
  id: '__root__' | '/' | '/ai-guide' | '/privacy' | '/r' | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiGuideRoute: typeof AiGuideRoute
  PrivacyRoute: typeof PrivacyRoute
  RRoute: typeof RRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r': {
      id: '/r'
      path: '/r'
      fullPath: '/r'
      preLoaderRoute: typeof RRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-guide': {
      id: '/ai-guide'
      path: '/ai-guide'
      fullPath: '/ai-guide'
      preLoaderRoute: typeof AiGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiGuideRoute: AiGuideRoute,
  PrivacyRoute: PrivacyRoute,
  RRoute: RRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
